### ISSUE TITLE
fl_draw_image with FL_RGB_SCALING_BILINEAR sometimes crashes when window is scaled

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1134]
**Describe the bug**

While updating a few image-heavy FLTK 1.3 applications to 1.4, I noticed a technique used to scale an image down by half; by multiplying fl_draw_image's `D` parameter by 2 (to skip every other pixel) and multiplying the `L` parameter by 2 (to skip every other row).

As far as I can tell, this is totally valid, but it causes FLTK to crash only when `FL_RGB_SCALING_BILINEAR` is used (1.4's default behavior).
(There is no crash with `FL_RGB_SCALING_NEAREST`, ie original FLTK 1.3 behavior.)

The crash happens only when the window is scaled up or down. It does not crash at 100% scale.

**To Reproduce**

```cpp
#include <FL/Fl.H>
#include <FL/fl_draw.H>
#include <FL/Fl_PNG_Image.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Radio_Round_Button.H>

#include <cassert>

Fl_RGB_Image *tile = nullptr;
Fl_Window *window = nullptr;

class Canvas : public Fl_Widget {
public:
    Canvas(int x, int y, int w, int h, char *l=nullptr) : Fl_Widget(x, y, w, h, l) {}

    void draw() {
        fl_draw_image(tile->array,
            150, 150,
            tile->w() / 2, tile->h() / 2, // scale the image in half
            tile->d() * 2,                // skip every other pixel
            tile->w() * tile->d() * 2     // skip every other row
        );
    }
};

void use_nearest_cb(Fl_Widget *w, void *d) {
    Fl_Image::scaling_algorithm(FL_RGB_SCALING_NEAREST);
    window->redraw();
}

void use_bilinear_cb(Fl_Widget *w, void *d) {
    Fl_Image::scaling_algorithm(FL_RGB_SCALING_BILINEAR);
    window->redraw();
}

int main(int argc, char **argv) {
    tile = new Fl_PNG_Image("tile.png");
    assert(tile->w() == 16);
    assert(tile->h() == 16);
    assert(tile->d() == 3);

    window = new Fl_Window(200, 200, 300, 300);
    Fl_Radio_Round_Button *radio1 = new Fl_Radio_Round_Button(10, 10, 280, 20, "Use FL_RGB_SCALING_NEAREST");
    Fl_Radio_Round_Button *radio2 = new Fl_Radio_Round_Button(10, 50, 280, 20, "Use FL_RGB_SCALING_BILINEAR");
    Canvas *canvas = new Canvas(0, 0, 300, 300);
    window->end();

    window->resizable(nullptr);
    radio1->setonly();
    radio1->callback(use_nearest_cb);
    radio2->callback(use_bilinear_cb);

    use_nearest_cb(nullptr, nullptr);

    window->show(argc, argv);
    return Fl::run();
}
```

Use the following image and name it "tile.png":

![tile](https://github.com/user-attachments/assets/b7fbbbb6-c98a-4ca3-aabc-16c5e3b53349)

This image has a black pixel in the top-left of every 2x2 square and a red pixel everywhere else. All red pixels should be skipped.

1. Compile the above demo.cxx and run.
2. Notice that only black pixels are drawn.
3. With FL_RGB_SCALING_NEAREST selected, notice that the window scales up and down without issue.
4. With FL_RGB_SCALING_BILINEAR selected, notice that the program crashes when the window is scaled up or down too much.

**Expected behavior**

FL_RGB_SCALING_BILINEAR shouldn't cause fl_draw_image to crash when a technique like skipping every other pixel/row is used.

**Video**

https://github.com/user-attachments/assets/2b196c58-9d05-43d0-baf4-06d1ac4bee4c

![image](https://github.com/user-attachments/assets/6d69725c-5e07-4c8d-8383-ced2d3daec1a)

> Run-Time Check Failure # 2 - Stack around the variable 'downright' was corrupted.

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 2cd0ec7

**FLTK Configure / Build Options**
 - Default VS CMake options

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 11
 - Processor if relevant: Intel

**Additional context**

I've tested this so far only on Windows, but it may or may not happen on other platforms.

**Comment by ManoloFLTK** [comment]
We should be good with the commmit mentioned above.

**Comment by Albrecht-S** [comment]
@ManoloFLTK wrote:
> We should be good with commit c6d480352b24e9cbfaf6bd46d0a8d28b5475b7e0

FTR: ... which is the last of three commits, starting with 619677b75c19173e26adf88f02870b5721f82736.

The two further commits were required to export two new (previously inline) functions to build a shared library on Windows, at least with Visual Studio (see CI build failure).

Note that the first commit breaks (i.e. extends) the ABI by making two inline methods "real" methods that need to be exported.

@ManoloFLTK Thoughts and questions:
1. It is basically OK to extend the ABI by adding new functions/methods but then we need to release 1.4.1 (soon) to cleanup. Quick follow-up releases until the 1.4.x code settles are planned anyway, hence this is possible.
2. Was it really necessary to expose these two methods in the first place? Is there maybe a better solution?
3. Unchecked: if we left the status as-is, wouldn't these two methods need documentation?

**Comment by dannye** [comment]
> We should be good with commit [c6d4803](https://github.com/fltk/fltk/commit/c6d480352b24e9cbfaf6bd46d0a8d28b5475b7e0).

Looks fixed to me! (Tested on Windows.)
Thanks very much, @ManoloFLTK, as always. Feel free to close this issue whenever you're satisfied with the follow-up discussion.

**Comment by dannye** [comment]
I think I spotted a different crash caused by the fix.

Run test/image to see it:

![image](https://github.com/user-attachments/assets/d8dde381-3c80-49f4-b59d-8e497ac4ace7)

![image](https://github.com/user-attachments/assets/881a0f22-ef3a-489d-a30e-076200f54db2)

**Comment by ManoloFLTK** [comment]
@Albrecht-S The further commit (1f05a0d) should fix the ABI issue because the 2 functions that lost before their inline status are now inline again.

@dannye This commit should also fix the issue visible with test/image. I had before forgotten to take into account the `FL_IMAGE_WITH_ALPHA` flag.

**Comment by MatthiasWM** [comment]
@ManoloFLTK Could you please take another look. XPM's still don't have their alpha channel rendered correctly. This is FLUID on macOS M1 Sequoia and Xcode 16.1:

![Screenshot 2024-11-20 at 08 33 50](https://github.com/user-attachments/assets/ca647efd-2ac2-438d-a82d-fbc54cd823ba)

**Comment by ManoloFLTK** [comment]
We should be good with commit 0952d59. The API for fl_draw_image(buf,X,Y,W,H,D,L) is very bad. When D=4 does it mean we want to draw a depth-4 image? or that we want to skip 4 bytes between successive 3-byte color pixels? or between successive 1-byte gray level pixels?

**Comment by MatthiasWM** [comment]
Yes, the API is old. 1 means grayscale, 2 means gray plus alpha, 3 means RGB, 4 means RGBA. The data is always expected to be packed with 8 bits per component. We would need an additional argument to allow RGBx, ARGB, and all those other formats. But this is a bottomless pit. In OpenGL, the `type` and `format` parameters [here](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml) give a nice idea of the formats out there. For FLTK, the developer is in control how to store the pixel data internally, so I don't see so much of a need. FLTK is not an image processing software.

Oh, and 0952d594f8f62d04880d7c0d743e6aab3c77e59b did fix the issue. Thank you!

**Comment by ManoloFLTK** [comment]
@Albrecht-S Please, close issue if you agree the problem with ABI has disappeared. Any further discussion about the last 2 arguments of `fl_draw_image()` should go elsewhere, if it's needed.

**Comment by dannye** [comment]
Just confirming one more time that everything looks fixed after the latest changes (tested on Windows and Linux). Thank you.
