### ISSUE TITLE
Full screen broken on macOS in FLTK 1.3.10 (regression)

### ISSUE THREAD

**Issue by CendioOssman** [fltk/fltk#1192]
**Describe the bug**
Full screen no longer works reliably in FLTK 1.3.10. It either gets confused about the state, or fails to update the state.

**To Reproduce**
1. Start TigerVNC
2. Connect to a server
3. Press "F8" and enable full screen

**Expected behavior**
TigerVNC enters full screen

**FLTK Version**
 - Version: 1.3.10
 - Installed as package from: homebrew
 - Downloaded and self-built from: git (second test)
 - If from Git, branch: branch-1.3
 - If from Git, commit: 9ed7752fa167cd60c1730e43a641c43cec5a3224

**FLTK Configure / Build Options**
 - cmake -S . -B build

**Operating System / Platform:**
 - OS: macOS
 - OS Version: 15.2
 - Processor if relevant: M1

**Additional context**
This is a regression caused by 20e2879.

The primary issue is that this commit enables macOS native full-screen functionality. I have not investigated any details of why this switch fails, as the native full-screen functionality is inherently incompatible with multi-head (which FLTK supports, and TigerVNC needs).

As such, we require some way to fully opt out of the native full-screen functionality.

**Comment by CendioOssman** [comment]
Reverting that commit returns to a mostly sane behaviour. But there is also a crash that's been around for a while:

You can still enter native full screen by pressing the green button on the window. If you then try to leave full screen via FLTK (via the F8 menu in TigerVNC), it crashes with:

```
2025-01-22 13:22:24.409 vncviewer[21541:346029] NSWindowStyleMaskFullScreen cleared on a window outside of a full screen transition. Called from (
```

It would probably be prudent to disable that path by doing:

```objc
win.collectionBehavior |= NSWindowCollectionBehaviorFullScreenNone;
```

**Comment by dannye** [comment]
@CendioOssman

> there is also a crash that's been around for a while:
> 
> You can still enter native full screen by pressing the green button on the window. If you then try to leave full screen via FLTK (via the F8 menu in TigerVNC), it crashes with:
> 
> ```
> 2025-01-22 13:22:24.409 vncviewer[21541:346029] NSWindowStyleMaskFullScreen cleared on a window outside of a full screen transition. Called from (
> ```

That crash was fixed in #924, and I assume that commit 20e2879 is (at least in part) the branch-1.3 equivalent of the 1.4 fix from that issue report. So if you revert that commit, it makes sense that you would start seeing that crash. IMO, FLTK's better native-fullscreen support is very important. It sounds like perhaps what you really want is for your F8 handler to make the window borderless+maximized?

That being said, I'm actually not sure if there is an FLTK API to disable the native green fullscreen button, which you would probably be interested in to full avoid native fullscreen.

Other related issues may be #920 and #1098.

**Comment by CendioOssman** [comment]
> 1. What **does** happen if you press F8? Is there any reaction at all, or what does "no longer works reliably" mean? [¹]

Sorry, I thought I included that. I've seen three variants:

1. Nothing happens
2. It enters full screen, then promptly leaves
3. Like 2., but it ends up in a loop constantly toggling full screen on and off

> What FLTK function is called when F8 is pressed in TigerVNC?

`Fl_Window::fullscreen_screens()` and `Fl_Window::fullscreen()`. The main work horse for that is here:

https://github.com/TigerVNC/tigervnc/blob/f5b42e4085cf11ea1d6395c470e3f1c10df31daa/vncviewer/DesktopWindow.cxx#L964

> [@CendioOssman](https://github.com/CendioOssman) Can you or someone else please try FLTK 1.4.1 (or better branch `master`) to see if this is fixed in `master`?

TigerVNC is not ported to FLTK 1.4 yet, so unfortunately that's not easily done. At least not with reliable results.

**Comment by CendioOssman** [comment]
The loss of functionality can be easily tested using the included "fullscreen" test application. 20e2879ea8205934aeb3d31377bd3645439f4010 makes the setting "All Screens" do nothing. I can see if I can test that on 1.4.1.

(Note that your mac needs to be configured without "Displays have separate spaces" to allow multihead full screen)

I did not see the other weirdness with that simple test application. So that might be a more complex issue involving event propagation and responses to that.

**Comment by CendioOssman** [comment]
> The loss of functionality can be easily tested using the included "fullscreen" test application. [20e2879](https://github.com/fltk/fltk/commit/20e2879ea8205934aeb3d31377bd3645439f4010) makes the setting "All Screens" do nothing. I can see if I can test that on 1.4.1.

Same regression on `master`. If I revert 0818d4ec5ba17314187f612a88814b02ae24b710, then functionality is restored.

**Comment by ManoloFLTK** [comment]
@CendioOssman The solution is probably as @dannye suggested to make your window borderless and maximized which should give the equivalent of what was an FLTK fullscreen window before 20e2879. A problem is that Fl_Window::maximize() has not been backported to 1.3. Could you try that under 1.4 and report what you get?

**Comment by CendioOssman** [comment]
I tried it with the "fullscreen" app, and I'm afraid that does not work. Maximize does not respect `Fl_Window::fullscreen_screens()`, even without borders.

It is also not a particularly desirable outcome. We use a toolkit to abstract away the platform details and not have to have one implementation per OS.

**Comment by ManoloFLTK** [comment]
@CendioOssman Please forget about making the window borderless and maximized, the result is quite different from a fullscreen window. But I see that, using the `test/fullscreen` app, and with both FLTK 1.3.10 and 1.4, if the window is made borderless before clicking "All Screens" and "FullScreen", the result is a fullscreen window covering two screens when there are two. 

I see also that this patch to the `test/fullscreen` app makes the "All Screens" button work as what TigerVNC would like to get with the "F8" key :

[fullscreen.patch.txt](https://github.com/user-attachments/files/18517085/fullscreen.patch.txt)

Could you check if this approach would work in TigerVNC?

**Comment by ManoloFLTK** [comment]
@CendioOssman I add that the changes to `test/fullscreen` mentioned above are cross platform so could be used by TigerVNC in a platform-independent way. I've just checked they work, in addition to macOS, under X11, Wayland and Windows.

**Comment by ManoloFLTK** [comment]
@CendioOssman Commit 5c5a12d to branch-1.3 should fix this issue. Please, report here if you confirm. If so, I'll commit equivalent changes to master.

**Comment by CendioOssman** [comment]
Better, but I can still see two issues:
* It does relayer properly after losing focus and regaining it
* The crash is back when clicking the green caption button

**Comment by ManoloFLTK** [comment]
I do see a crash in `test/fullscreen` with these operations:
1. clik the "FullScreen" FLTK button or the green titlebar button
2. click "All Screens"

Is this the crash you reported?

This is now fixed at commit bfdae6d to branch-1.3.

**Comment by CendioOssman** [comment]
> Is this the crash you reported?

In TigerVNC it was sufficient to just click the titlebar button. But it seems to have been the same issue, as the crash is now gone. Thanks!

> * It doesn't relayer properly after losing focus and regaining it

Open TigerVNC or `test/fullsceen` in non-native full screen. Cmd+Tab to another application, then Cmd+Tab back. The top menu and dock are now incorrectly overlayed on top of the full screen application.

With the crash gone, there is still some confusing interaction between the titlebar button and the application. For `test/fullscreen`, its just that the setting "All Screens" isn't respected. TigerVNC gets a bit more confused, though. It seems to first enter native full screen. Then promptly configure the desired monitors, dropping it out if native full screen and in to the non-native one. The animations for all of this makes the user experience less than ideal.

**Comment by ManoloFLTK** [comment]
> Open TigerVNC or test/fullsceen in non-native full screen. Cmd+Tab to another application, then Cmd+Tab back. The top menu and dock are now incorrectly overlayed on top of the full screen application.

That should be fixed with commit ad333e2.

**Comment by CendioOssman** [comment]
Seems to work.

I think everything is back to FLTK 1.3.9 behaviour now. The only remaining issue is the confusing behaviour from the caption button, but that is not a regression.

It would be nice if FLTK could abstract that away in the future. For now, we've added this workaround:

https://github.com/TigerVNC/tigervnc/commit/f5b42e4085cf11ea1d6395c470e3f1c10df31daa

**Comment by ManoloFLTK** [comment]
I propose in a further commit (d7f0c8e) to make member function `Fl_Window::fullscreen_screens()` toggle the window's `NSWindowCollectionBehaviorFullScreenNone` flag. This way, the green button becomes a "maximize window" button when "All Screens" is on, and returns to a fullscreen button when "All Screens" is off. That should render your workaround unnecessary.

If we agree the issue is now fixed, I will reproduce the code changes in FLTK 1.4 too.

**Comment by CendioOssman** [comment]
Anything left to do here? We're hoping for a FLTK 1.3.11 so we can get TigerVNC 1.15.0 out the door.

**Comment by Albrecht-S** [comment]
> Anything left to do here? We're hoping for a FLTK 1.3.11 so we can get TigerVNC 1.15.0 out the door.

@CendioOssman I'm ready to release FLTK 1.3.11 within one or two days if you and @ManoloFLTK confirm that this issue is fixed and close it. I already prepared most of the remaining release work in a local branch, there's only the release announcement stuff left to be done.

Please confirm and close the issue.

**Comment by ManoloFLTK** [comment]
@CendioOssman Please, confirm whether everything runs OK in TigerVNC with all commits to FLTK branch 1.3. It's expected no workaround to be necessary anymore.

**Comment by CendioOssman** [comment]
Everything seems to work okay now. I'd say we're good to go ahead with a release.

I think we'll keep our workaround for a while, rather than do `Fl_Window::fullscreen_screens(0, 0, 0, 0);`, in case users aren't running the latest FLTK.

**Comment by Albrecht-S** [comment]
Thanks for confirmation, @CendioOssman and @ManoloFLTK.

I'm closing the issue now and I'll release 1.3.11, likely during the next two days.

FTR: There are no more releases of the 1.3.x series planned in the future.

**Comment by CendioHalim** [comment]
Hmm, something seems broken.

Using branch-1.3, I tried building TigerVNC-master and the ThinLinc client (TigerVNC 1.12.80), and full screen does not work on macOS on either of them. Both of the builds were with an old macOS SDK version (10.6), and an old GCC (5.5.0). I think the builds @CendioOssman did were on a modern mac.

Reverting patch 20e2879ea8205934aeb3d31377bd3645439f4010 resolves this issue for me. I'll come back after some investigation with more details.

**Comment by ManoloFLTK** [comment]
@CendioHalim Yes. I can see now that some 
`#if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_7 / #endif`
clauses were not placed correctly and inhibited fullscreen mode when building with SDK 10.6.
That should be fixed with commit c970ab9.

I did not expect such old an SDK version to be still in use! That gives me the opportunity to stress that FLTK is conceived to support building with recent SDK versions and running on old macOS versions, obviously not forgetting to set option -mmacosx-version-min= to the oldest macOS version for which support is desired.

**Comment by CendioHalim** [comment]
@ManoloFLTK 

I tested building TigerVNC with your commit and can confirm that it resolved the issue for me, both on the 10.6 SDK, and on a new Mac. 

Thank you for responding and resolving this issue so quickly.

**Comment by CendioHalim** [comment]
@ManoloFLTK 

Looks like there is still an issue with full screen when building on SDK 10.6.

If I run TigerVNC in full screen, and then lose focus by clicking on another screen or by opening a menu (e.g. F8 -> Options), the system menu bar & launcher are permanently visible.

I can confirm that full screen works properly with version 1.3.7.

**Comment by CendioHalim** [comment]
@ManoloFLTK 

Tested using TigerVNC with your latest commit and can confirm it works for me.

Thanks for the fix.
