### ISSUE TITLE
SVG rendering spoiled by scaling

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#155]
On Xlib with XRender enabled, I'm observing "unexplainable" drawing artefacts with SVG images.

Some debugging shows, they come from a transformation matrix applied by drawing via XRender:

When an SVG image is drawn it first gets rasterized. After that its w() and h() are equal to its data_w() and data_h().
Somehow in the drawing process the w() and/or h() are getting bigger values (by cache_size() ??). Afterwards when beeing drawn with Fl_Xlib_Graphic_Driver_image::scale_and_render_pixmap  a XRender transformation matrix is applied, because w()/data_w() and/or h()/data_h() are !=1, leading to artefacts in the already perfectly rendered image.

I think it can happen either when a screen scaling factor is set for FLTK and/or when an SVG image is scaled into a container with the proportional flag set.

Is there anything that can be done to avoid the transformation?

**Comment by ManoloFLTK** [comment]
A small example code would be helpful.

**Comment by wcout** [comment]
Attaching source with a test svg and a picture of the output.

The SVG is rasterized to 169x97 but has a data_w of 170 before calling scale_and_render_bitmap, so the scale_x gets set to 0.994118. The screen scaling  factor is 1.

As you see in the screenshot there is an artefact on the right side of the letter O, that is not present on the rasterized image produced by nanosvg.

[svg_test.zip](https://github.com/fltk/fltk/files/5518524/svg_test.zip)
![output](https://user-images.githubusercontent.com/9895976/98698559-74587780-2376-11eb-81f6-bd0b429081be.png)

Note that is just one way to create this situation, there are probably other ways (especially when a scale factor is on the whole screen) that can lead to it.

**Comment by ManoloFLTK** [comment]
Many thanks for the test source code.
I believe this issue is now fixed in the git repository,  for FLTK 1.4.

Can the OP, please, confirm?

**Comment by wcout** [comment]
Unfortunately it does not fix the issue in all cases, it does for the reported case. But setting the screen scale there are still artefacts.
You can see it with the test program when setting screen scale to e.g. 1.9 (and many others):

![scale_1_9](https://user-images.githubusercontent.com/9895976/98779924-aa3c4100-23f4-11eb-9d41-e735d295a4ac.png)

I have put some printf's into the Fl_Xlib_Graphics_Driver_image.cxx to the see, when the transformation is called and show the image dimensions used to set up the scale factors - the output is:

test.svg at scale 1.500000: 170 x 98 (4000 x 2300)
256 x 148 (256 x 147)
XRender transform 1.000000 / 0.993243

test.svg at scale 1.600000: 170 x 98 (4000 x 2300)
273 x 158 (273 x 157)
XRender transform 1.000000 / 0.993671

test.svg at scale 1.700000: 170 x 98 (4000 x 2300)
290 x 168 (290 x 167)
XRender transform 1.000000 / 0.994048

test.svg at scale 1.800000: 170 x 98 (4000 x 2300)
307 x 178 (307 x 177)
XRender transform 1.000000 / 0.994382

test.svg at scale 1.900000: 170 x 98 (4000 x 2300)
324 x 188 (324 x 186)
XRender transform 1.000000 / 0.989362

**Comment by ManoloFLTK** [comment]
I believe a general fix is now committed in the git repository, for the X11 platform.

Can the OP, please, report her/his findings ?

**Comment by wcout** [comment]
I see a huge improvement with the test program.

But trying to port the gist of your change back to the slightly older FLTK version of my application I see no improvement, in the contrary much more and worse of these artefacts! So dunno if i missed something (though I double checked) and what to say.

I the meanwhile I was trying to work around the artefacts by checking the scales in `scale_and_render_pixmap()` and if both are very near to 1.0 ( I used <0.01 difference), then do not setup the transformation. This works, but of course is no solution. 

BTW: Currentyl I get a linker error for the test programs with latest Commit:
```
Linking unittests...
/usr/bin/ld: ../lib/libfltk.a(Fl_Graphics_Driver.o): in function `Fl_Graphics_Driver::cache_size(Fl_Image*, int&, int&)':
Fl_Graphics_Driver.cxx:(.text._ZN18Fl_Graphics_Driver10cache_sizeEP8Fl_ImageRiS2_+0x8b): undefined reference to `Fl_SVG_Image::cache_size(int&, int&)'
collect2: error: ld returned 1 exit status
```

**Comment by Albrecht-S** [comment]
@ManoloFLTK Please see @wcout's message above (failed build) and the [build log at Travis-CI](https://github.com/fltk/fltk/runs/1389024709). Thanks.

PS: just in case you didn't know: you can click on the referenced commit 231159e16c above, then on the red cross to see the "Details" and follow the link. The same works in the "commit view" of our repo.

**Comment by ManoloFLTK** [comment]
@wcout:  the expectation with the new code is that both scales in scale_and_render_pixmap()
are exactly equal to 1, so you would not have to "work around". If that's not the case,
an example .svg file would be helpful.

@Albrecht: build should be OK now

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thanks, commit a4bacf8 looks like a real improvement: making that specific method virtual and removing the necessity to call as_svg_image() - great move ;-)

**Comment by wcout** [comment]
Good news: I've temporarily built my application with the latest commit (instead of back-porting the changes) and ... Hooray! ...**no more artefacts!** 
I will test more thoroughly later, but for now this issue seems solved.
Thank you very much for tackling it so quickly. Chapeau!

**Comment by wcout** [comment]
@ManoloFLTK I believe the `friend class Fl_Graphics_Driver` in `Fl_SVG_Image.H` is not needed any more.

**Comment by ManoloFLTK** [comment]
@wcout: please, don't ommit to report the outcome of your more thorough tests.
I have just removed this unnecessary friend declaration.

**Comment by wcout** [comment]
This issue is fixed for me under Xlib. I can't test other platforms though.
I confirm the SVG scaling now works without additional software distortion with and w/o Xrender.
