### ISSUE TITLE
Suggestion: pass the focus state as a parameter to `Fl_Input_::drawtext`

### ISSUE THREAD

**Issue by Rangi42** [fltk/fltk#211]
`Fl_Input::draw` and `Fl_File_Input::draw` both call `Fl_Input_::drawtext` to do the majority of their drawing. This method has repeated checks for whether `Fl::focus() == this`, which control whether to draw the cursor and selection. If `Fl::focus() == this` were passed to `drawtext` as a `bool focused` parameter, it would be easier to extend the `Fl_Input` class for custom grouped widgets. The `drawtext` method does not modify the focus state, so it would be valid as a passed parameter.

(My own use case is an `Fl_Input` that pops up an `Fl_Browser` with autocomplete suggestions within an `Fl_Menu_Window` when you start typing. So far it passes events down to the `Fl_Input` so the popup menu can coexist with continuing to type, but the cursor and selection do not show up.)

**Comment by Rangi42** [comment]
Related: in a new API version, `Fl_Input::handle_key` could be `protected`, not `private`.

**Comment by Albrecht-S** [comment]
@Rangi42: Thanks for your suggestions.
> in a new API version, Fl_Input::handle_key could be protected, not private.

Done in commit 22cb8a7fdb1d.

**Comment by Albrecht-S** [comment]
> Fl_Input_::drawtext ... has repeated checks for whether Fl::focus() == this, ...

Your suggestion to add `Fl::focus() == this` as a boolean parameter: `Fl::focus()` is a very fast inline method, it's just a memory lookup - there's not much potential for optimization if that's what you want to achieve. Thoughts:

- I don't think it's useful to add this extra argument - unless there's a compelling reason to pass a **different** information.
- In fact someone could pass the **wrong** information.
- Information hiding: the implementation doesn't require this argument, so don't force the caller to set it (there's no need to expose implementation details to the caller).
- If we ever wanted to "optimize" that code we could store `Fl::focus() == this` in a local variable and subsequently use this variable.
- The compiler would (probably) do this for us anyway, at least if compiled with optimization.

That said, I propose to close this issue. Thanks for your second suggestion which has been committed.

If you have more comments or questions, please feel free to comment - or to close this issue.

**Comment by Rangi42** [comment]
My concern wasn't optimization, but being able to draw an unfocused input that still shows its cursor, by passing `true` instead of `Fl::focus() == this`. Otherwise a class extending `Fl_Input` with its own `draw` method would just have to replicate much of `drawtext` on its own.

**Comment by Albrecht-S** [comment]
Okay, I see, thanks for your comment. I'll take another look at the code, but please don't hold your breath - I'm pretty busy these days.

I removed the `wontfix` label for now, but that's no guarantee that it **will** be implemented as requested.

**Comment by MatthiasWM** [comment]
Fixed in [ee4ab86](https://github.com/fltk/fltk/commit/ee4ab86c3cbf8d03ea3bf0441943fc6928d91f09)

**Comment by Albrecht-S** [comment]
@MatthiasWM Thanks for fixing this. I assigned you (and me earlier) for reference, and I also adjusted the labels, just for our statistics.
