### ISSUE TITLE
fluid -c crashes on Linux

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#514]
**Describe the bug**
Invoking `fluid -c` without arguments from the command-line causes a segmentation fault.

**To Reproduce**
Call fluid -c without arguments:
```
$ fluid -c
```

N/A

**Expected behavior**
A file dialog opens on macos for example. Or maybe a help menu should be printed to the console.

**Screenshots**
N/A

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0
 - Built from source via CMake

**FLTK Configure / Build Options**
 - cmake -Bbin -DCMAKE_BUILD_TYPE=Release -DFLTK_BUILD_EXAMPLES=OFF -DFLTK_BUILD_TEST=OFF && cmake --build bin --target install

**Operating System / Platform:**
Linux: Ubuntu 20.04 on WSL

**Linux/Unix Runtime, if applicable:**
 - X11

**Comment by ManoloFLTK** [comment]
This should be fixed with commit 531ab61. 
@MoAlyousef : Please, close if you confirm.

**Comment by MoAlyousef** [comment]
Hi @ManoloFLTK 
Thanks, this is indeed fixed.

**Comment by Albrecht-S** [comment]
Sorry, this quick fix is good in itself (no need to revert it) but it does not really fix the issue "`fluid -c` w/o argument" because ...

... the file chooser dialog opens a file for "**saving**" which is unexpected and unintuitive.
- If you select an existing file you are asked "Do you want to replace it?" and fluid would overwrite the file if answered with "yes".
- If you select a non-existing file fluid writes an (almost) empty file and the corresponding .cxx and .h files.

A better fix would be to reject the request with a help message that an input file is required as @MoAlyousef suggested.

Reopening this issue.

**Comment by Albrecht-S** [comment]
The same would very likely be true if `fluid -u` is used w/o argument.
