### ISSUE TITLE
Installing a custom cursor works fine in MacOS but not in Linux

### ISSUE THREAD

**Issue by olarroche** [fltk/fltk#520]
**Describe the bug**
I modified the cursor.cxx test program to add the possibility of using a custom-defined cursor. This works as expected on MacOS, but on a Linux machine, the custom cursor is not used when requested by the Fl_Window::cursor() method, and the default cursor is used instead.

**To Reproduce**
A small tarball is attached, with a .cxx source and a makefile. The source is a modification of the cursor.cxx FLTK test program, defining a custom cursor from a provided Fl_RGB_Image, in addition to the cursors in the Fl_Cursor enumeration. The custom cursor is selected by an additional entry in the menu in cursor.cxx. A button is added to display the provided Fl_RGB_Image, which works fine on MacOS and Linux. But on my Linux laptop under Ubuntu 18.04, the cursor I defined is not used as a cursor image when cursor() is called, although it works fine on two Macs I have access to : a MacPro under MacOS 10.13.6 with fltk 1.3.3 and a MacStudio under MacOS 12.6 with fltk 1.3.8.

**FLTK Version**
 - Version: 1.3.8
 - Downloaded and self-built from tarball

**FLTK Configure / Build Options**
I built FLTK by just typing "make", with no specific options.

**Operating System / Platform:**
 - OS: Linux Ubuntu 18.04 on a DELL laptop

[cursor_OL.tar.gz](https://github.com/fltk/fltk/files/9827946/cursor_OL.tar.gz)

**Comment by Albrecht-S** [comment]
Thanks for the report and the demo program.

However, this works fine for me on Linux Mint 20 (and macOS and Windows, BTW) using FLTK 1.4.0 (master).

Tested successfully also on Linux Mint 20 (based on Ubuntu 20.04) with FLTK 1.3.8:
- git branch `branch-1.3` and
- git tag `release-1.3.8`.

Note: I used `./fltk-config --compile cursor_OL.cxx` to build the program (didn't use the provided Makefile).

**Comment by Albrecht-S** [comment]
Is it possible that you have another FLTK version installed on your system? If yes you might have created a mixed build of headers from one version and the library from another version.

Please try my command above (modified as required) to ensure that this is not the case.

Side note: `--use-images` is not necessary for your demo program (but this is irrelevant for the issue).

**Comment by olarroche** [comment]
Hi Albrecht

Thanks for taking a look at this problem. I recompiled cursor_OL.cxx using your command, but I still get the same result : OK on my Mac, custom cursor not installed (default cursor used instead) on my Linux laptop... 

If it can be of any help, here is the actual command produced by fltk-config --compile on the Linux laptop:

g++ -I/usr/local/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT -o 'cursor_OL' 'cursor_OL.cxx' /usr/local/lib/libfltk.a -lXrender -lXfixes -lXext -lXft -lfontconfig -lpthread -ldl -lm -lX11

I installed the libraries required as per the README.Unix.txt file (including the optional ones), but maybe there is some conflict with other libraries linked with the program ?

Or maybe there is something wrong with my Fl_Image ? The cursor() method is obviously called, but changes the cursor to the default, which, according to fltk.pdf, means that my image "cannot be used as a cursor"... Well, but it does work on my Mac... and on all your machines as well.

Anyway, thanks for your answer, have a good day
Olivier

**Comment by olarroche** [comment]
Oh, and I also compiled using the local include files and library, which replaces -I/usr/local/include with -Ifltk-1.3.8 and /usr/local/lib/libfltk.a with fltk-1.3.8/lib/libfltk.a (fltk-1.3.8 is the directory created when unpacking the distribution, my source lives just next to it). So if I understand your point, this way I'm sure I use the correct stuff for linking, but the result is the same.

**Comment by Albrecht-S** [comment]
> [description using the FLTK build directory to build] So if I understand your point, this way I'm sure I use the correct stuff for linking, but the result is the same.

Yes, that was the point I meant. It's strange that it works for me but not for you.

Please try FLTK 1.4.0, i.e. download today's snapshot, build FLTK, and then try your program as before, with `./fltk-config ...` in the FLTK 1.4 build directory, just to be sure. You can also replace test/cursor.cxx with your modified source and test what happens when you build FLTK which will create the modified test/cursor program.

**Comment by olarroche** [comment]
Ahem... I just dowloaded and compiled today's fltk-1.4, re-compiled cursor_OL.cxx with this (btw, the final linked code is larger and larger... ;-) ), but... same problem !

Well, to be continued...

**Comment by olarroche** [comment]
Me again ;-)

I put some printf's in Fl_x.cxx, recompiled fltk and my test program, and it turns out that in method Fl_X::set_cursor(), we leave prematurely because we don't HAVE_XCURSOR ... How can such things happen ?

**Comment by MoAlyousef** [comment]
You probably don’t have libxcursor headers. 
You can try running:
`apt-get install libxcursor-dev`
This will require recompiling FLTK.

**Comment by olarroche** [comment]
Yes !

Thanks for the tip, it works now. Maybe a line could be added in README.Unix.txt advising users to install this piece of software ?

Thanks to both of you, have a good day
Olivier

**Comment by Albrecht-S** [comment]
@olarroche Welcome. I'm glad you found it, thanks to your debugging and the help of ...

@MoAlyousef Awesome, your help is always great and very much appreciated.

@olarroche I updated README.Unix.txt as suggested and I hope it's more complete now. Thanks for the heads-up.

Can we close this issue now?

**Comment by olarroche** [comment]
Hello
Yes, this specific issue has received a satisfactory answer.
However, I'm still having some cursor problems that I have to sort out in the app I'm developing, and maybe you will hear from me again in the future... ;-)
