### ISSUE TITLE
Screen resolution change (win32)

### ISSUE THREAD

**Issue by lesha-red** [fltk/fltk#651]
**Describe the bug**
While any FLTK window is open, if I change screen resolution, this sample program never exits. I suppose there is a bug in WM_DISPLAYCHANGE handling.

Fl_ScreenDriver.cxx:

Fl_Window_Driver::driver(win)->resize_after_scale_change(screen, old_f, f); 
win->wait_for_expose();  // -- hangs on this line

**To Reproduce**
#include <FL/Fl_Window.H>

int main(int argc, char **argv)
{
    auto win = new Fl_Window(100, 100, 300, 300, "test");
    win->show();
    Fl::run();
    return 0;
}

**FLTK Version**
 - Version: [experimental-2022-01](https://github.com/fltk/fltk/releases/tag/experimental-2022-01)
 - Downloaded and self-built from: Git
 - If from Git, commit: tag experimental-2022-01

**FLTK Configure / Build Options**
 - cmake -G"..." -DCMAKE_BUILD_TYPE=Debug ...

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 10

**Comment by Albrecht-S** [comment]
Hi @lesha-red, thank you for your report, however, the tag you mention is very, very old. It exists only to mark a very old commit before we removed some experimental features.

I assume that the bug you mention is already fixed and I could not reproduce it with the tag you mentioned under `wine`.

Please try again with a later commit from git `master`. If you don't have `git` please use a recent snapshot from our [Download](https://www.fltk.org/software.php) page or the latest release 1.3.8.

Please confirm if the bug you report does no longer exist.

**Comment by lesha-red** [comment]
I tried the same with commit 76a5c7b081361c2588c53253db374de5dd825cf9 (latest in master branch at the moment) and the problem still exists.

Stack trace, when the hang occurs:

Fl::wait Fl.cxx:585
Fl::wait Fl.cxx:627
Fl_Window_Driver::wait_for_expose Fl_Window_Driver.cxx:218
Fl_Window::wait_for_expose Fl_Window.cxx:465
Fl_Screen_Driver::rescale_all_windows_from_screen Fl_Screen_Driver.cxx:380
WndProc Fl_win32.cxx:1708
AddClipboardFormatListener 0x000000007525141b
GetClassLongW 0x00000000752483ca
ms2fltk Fl_win32.cxx:1229
<unknown> 0x00000000000e0dce
<unknown> 0x000000000000007e
<unknown> 0x0000000000000020
<unknown> 0x0000000004380780
GetClassLongW 0x0000000075247fca
ms2fltk Fl_win32.cxx:1229
<unknown> 0x0000000000000000

**Comment by Albrecht-S** [comment]
@lesha-red Thank you for testing again with the latest version. I'll look into it (or maybe another dev) but I have two questions:

1. You wrote `cmake -G"..." -DCMAKE_BUILD_TYPE=Debug ...` but you left out the generator. Which generator, i.e. `-G"..."` did you use? This may be important for testing.

2. You also wrote:
> While any FLTK window is open, if I change screen resolution, this sample program never exits

Do I understand correctly that you change the display resolution via system settings, i.e. you select another zoom factor? Please elaborate how you do this - again, this is important for testing.

Thank you in advance.

**Comment by lesha-red** [comment]
@Albrecht-S Thank you for input.

1. I'm using -G "Ninja" (MINGW 32-bit (sic!) environment). 

2. The error occurs when I change the display resolution via system settings (for example, it was 800x600 and I set it to 1024x768). Also, it occurs when I'm running the test program in Hyper-V VM and change Hyper-V guest window size.

As i digged up, after receiving WM_DISPLAYCHANGE, FLTK resizes windows and waits for WM_PAINT event, but never receives it.

**Comment by Albrecht-S** [comment]
_[I just saw your new message appear while I was writing this one. I'll read and reply to yours after I send this comment. Please ignore the questions you answered already]_

Hmm, meanwhile I tested on Windows (in my Virtualbox VM hosted on Linux) and I can't confirm the issue. My test scenario was to change the "Scale and layout" setting in "Display" (right click on desktop to open) and I changed scaling from 100% to 125% and vice versa.

I tried both Visual Studio 2019 and MSYS2 (mingw-w64, 64-bit) and everything works well. The window is rescaled as expected and still responsive. I used your posted example, test/hello.cxx, and test/buttons.cxx. The latter to test responsiveness.

- Did you do something else?
- Is there anything special with your build system?
- What is your Visual Studio version (if applicable)?
- Or what other build tools (e.g. MinGW) are you using (and which version)?

I'm puzzled...

**Comment by Albrecht-S** [comment]
OK, I just managed to bring `buttons.exe` into a "hanging" state. It executes at high CPU load and I'm trying to attach a debugger...

**Comment by Albrecht-S** [comment]
Thank you for your further info.
I tried several steps:
1. changed display resolution via setup (100% <-> 125%)
2. changed display resolution by setting another screen size (width x height)
3. changed the VirtualBox guest window size of my VM.

I'm not sure yet which one caused the "hanging" process (probably # 3), but I used the chance to attach the debugger (gdb) and I could get a stack trace. I couldn't debug it further yet, but what you write about waiting for `WM_PAINT` looks plausible. Further investigation is necessary.

This is the relevant part of my gdb session with the backtrace:
```
$ gdb -p 472
GNU gdb (GDB) 12.1
...
Attaching to process 472
...
(gdb) t 1
[Switching to thread 1 (Thread 472.0xf98)]
#0  Fl::wait () at E:/git/fltk/master/src/Fl.cxx:626
626       if (!Fl_X::first) return 0;
(gdb) bt
#0  Fl::wait () at E:/git/fltk/master/src/Fl.cxx:626
#1  0x00007ff7c588ebde in Fl_Window_Driver::wait_for_expose (this=0x1da681919a0) at E:/git/fltk/master/src/Fl_Window_Driver.cxx:218
#2  0x00007ff7c588d80f in Fl_Window::wait_for_expose (this=0x1da68191880) at E:/git/fltk/master/src/Fl_Window.cxx:465
#3  0x00007ff7c5886b10 in Fl_Screen_Driver::rescale_all_windows_from_screen (this=0x1da68196810, screen=0, f=1)
    at E:/git/fltk/master/src/Fl_Screen_Driver.cxx:380
#4  0x00007ff7c58a9689 in WndProc (hWnd=0x2004fc, uMsg=126, wParam=32, lParam=64292544) at E:/git/fltk/master/src/Fl_win32.cxx:1708
#5  0x00007ffdf301e7e8 in USER32!CallWindowProcW () from C:\Windows\System32\user32.dll
#6  0x00007ffdf301e36c in USER32!DispatchMessageW () from C:\Windows\System32\user32.dll
#7  0x00007ffdf30370f0 in USER32!GetIconInfo () from C:\Windows\System32\user32.dll
#8  0x00007ffdf3830ef4 in ntdll!KiUserCallbackDispatcher () from C:\Windows\SYSTEM32\ntdll.dll
#9  0x00007ffdf13f1064 in win32u!NtUserPeekMessage () from C:\Windows\System32\win32u.dll
#10 0x00007ffdf301a553 in USER32!PeekMessageW () from C:\Windows\System32\user32.dll
#11 0x00007ffdf301a4b3 in USER32!PeekMessageW () from C:\Windows\System32\user32.dll
#12 0x00007ff7c58a5c7f in Fl_WinAPI_System_Driver::wait (this=0x1da68191860, time_to_wait=0) at E:/git/fltk/master/src/Fl_win32.cxx:476
#13 0x00007ff7c5871f3d in Fl::wait (time_to_wait=1e+20) at E:/git/fltk/master/src/Fl.cxx:585
#14 0x00007ff7c5871fac in Fl::wait () at E:/git/fltk/master/src/Fl.cxx:627
#15 0x00007ff7c588ebde in Fl_Window_Driver::wait_for_expose (this=0x1da681919a0) at E:/git/fltk/master/src/Fl_Window_Driver.cxx:218
#16 0x00007ff7c588d80f in Fl_Window::wait_for_expose (this=0x1da68191880) at E:/git/fltk/master/src/Fl_Window.cxx:465
#17 0x00007ff7c5886b10 in Fl_Screen_Driver::rescale_all_windows_from_screen (this=0x1da68196810, screen=0, f=1)
    at E:/git/fltk/master/src/Fl_Screen_Driver.cxx:380
#18 0x00007ff7c58a9689 in WndProc (hWnd=0x2004fc, uMsg=126, wParam=32, lParam=64292575) at E:/git/fltk/master/src/Fl_win32.cxx:1708
#19 0x00007ffdf301e7e8 in USER32!CallWindowProcW () from C:\Windows\System32\user32.dll
#20 0x00007ffdf301e36c in USER32!DispatchMessageW () from C:\Windows\System32\user32.dll
#21 0x00007ffdf30370f0 in USER32!GetIconInfo () from C:\Windows\System32\user32.dll
#22 0x00007ffdf3830ef4 in ntdll!KiUserCallbackDispatcher () from C:\Windows\SYSTEM32\ntdll.dll
#23 0x00007ffdf13f1064 in win32u!NtUserPeekMessage () from C:\Windows\System32\win32u.dll
#24 0x00007ffdf301a553 in USER32!PeekMessageW () from C:\Windows\System32\user32.dll
#25 0x00007ffdf301a4b3 in USER32!PeekMessageW () from C:\Windows\System32\user32.dll
#26 0x00007ff7c58a5c7f in Fl_WinAPI_System_Driver::wait (this=0x1da68191860, time_to_wait=0) at E:/git/fltk/master/src/Fl_win32.cxx:476
#27 0x00007ff7c5871f3d in Fl::wait (time_to_wait=1e+20) at E:/git/fltk/master/src/Fl.cxx:585
#28 0x00007ff7c5871fac in Fl::wait () at E:/git/fltk/master/src/Fl.cxx:627
#29 0x00007ff7c588ebde in Fl_Window_Driver::wait_for_expose (this=0x1da681919a0) at E:/git/fltk/master/src/Fl_Window_Driver.cxx:218
#30 0x00007ff7c588d80f in Fl_Window::wait_for_expose (this=0x1da68191880) at E:/git/fltk/master/src/Fl_Window.cxx:465
#31 0x00007ff7c5886b10 in Fl_Screen_Driver::rescale_all_windows_from_screen (this=0x1da68196810, screen=0, f=1)
    at E:/git/fltk/master/src/Fl_Screen_Driver.cxx:380
#32 0x00007ff7c58a9689 in WndProc (hWnd=0x2004fc, uMsg=126, wParam=32, lParam=64292501) at E:/git/fltk/master/src/Fl_win32.cxx:1708
#33 0x00007ffdf301e7e8 in USER32!CallWindowProcW () from C:\Windows\System32\user32.dll
#34 0x00007ffdf301e36c in USER32!DispatchMessageW () from C:\Windows\System32\user32.dll
#35 0x00007ffdf30370f0 in USER32!GetIconInfo () from C:\Windows\System32\user32.dll
#36 0x00007ffdf3830ef4 in ntdll!KiUserCallbackDispatcher () from C:\Windows\SYSTEM32\ntdll.dll
#37 0x00007ffdf13f1064 in win32u!NtUserPeekMessage () from C:\Windows\System32\win32u.dll
#38 0x00007ffdf301a553 in USER32!PeekMessageW () from C:\Windows\System32\user32.dll
#39 0x00007ffdf301a4b3 in USER32!PeekMessageW () from C:\Windows\System32\user32.dll
#40 0x00007ff7c58a5c7f in Fl_WinAPI_System_Driver::wait (this=0x1da68191860, time_to_wait=0) at E:/git/fltk/master/src/Fl_win32.cxx:476
#41 0x00007ff7c5871f3d in Fl::wait (time_to_wait=1e+20) at E:/git/fltk/master/src/Fl.cxx:585
#42 0x00007ff7c5871fac in Fl::wait () at E:/git/fltk/master/src/Fl.cxx:627
#43 0x00007ff7c588ebde in Fl_Window_Driver::wait_for_expose (this=0x1da681919a0) at E:/git/fltk/master/src/Fl_Window_Driver.cxx:218
#44 0x00007ff7c588d80f in Fl_Window::wait_for_expose (this=0x1da68191880) at E:/git/fltk/master/src/Fl_Window.cxx:465
#45 0x00007ff7c5886b10 in Fl_Screen_Driver::rescale_all_windows_from_screen (this=0x1da68196810, screen=0, f=1)
    at E:/git/fltk/master/src/Fl_Screen_Driver.cxx:380
#46 0x00007ff7c58a9689 in WndProc (hWnd=0x2004fc, uMsg=126, wParam=32, lParam=56624256) at E:/git/fltk/master/src/Fl_win32.cxx:1708
#47 0x00007ffdf301e7e8 in USER32!CallWindowProcW () from C:\Windows\System32\user32.dll
#48 0x00007ffdf301e36c in USER32!DispatchMessageW () from C:\Windows\System32\user32.dll
#49 0x00007ffdf30370f0 in USER32!GetIconInfo () from C:\Windows\System32\user32.dll
#50 0x00007ffdf3830ef4 in ntdll!KiUserCallbackDispatcher () from C:\Windows\SYSTEM32\ntdll.dll
#51 0x00007ffdf13f1064 in win32u!NtUserPeekMessage () from C:\Windows\System32\win32u.dll
#52 0x00007ffdf301a553 in USER32!PeekMessageW () from C:\Windows\System32\user32.dll
#53 0x00007ffdf301a4b3 in USER32!PeekMessageW () from C:\Windows\System32\user32.dll
#54 0x00007ff7c58a5c7f in Fl_WinAPI_System_Driver::wait (this=0x1da68191860, time_to_wait=10000) at E:/git/fltk/master/src/Fl_win32.cxx:476
#55 0x00007ff7c5871f3d in Fl::wait (time_to_wait=1e+20) at E:/git/fltk/master/src/Fl.cxx:585
#56 0x00007ff7c5871f69 in Fl::run () at E:/git/fltk/master/src/Fl.cxx:605
#57 0x00007ff7c587177d in main (argc=1, argv=0x1da681917e0) at E:/git/fltk/master/test/buttons.cxx:39
(gdb) q
```

It looks as if there's a recursion in `Fl_Screen_Driver::rescale_all_windows_from_screen() at src/Fl_Screen_Driver.cxx:380` but this is only a first guess.

Files and line numbers are from git commit 76a5c7b081361c2588c53253db374de5dd825cf9.

**Comment by Albrecht-S** [comment]
Note: I set "Prio 3" because this (screen resolution change) is not expected to happen frequently but it is still a bug.

@ManoloFLTK Do you have an idea how to solve this issue?

**Comment by Albrecht-S** [comment]
OK, I had to give up for now. Let's see if @ManoloFLTK has an idea to debug this.

**Comment by lesha-red** [comment]
I fixed this for myself this way:

```
diff --git a/src/Fl_win32.cxx b/src/Fl_win32.cxx
index cdd9189a1..19b3d6fa5 100644
--- a/src/Fl_win32.cxx
+++ b/src/Fl_win32.cxx
@@ -1955,6 +1955,9 @@ void Fl_WinAPI_Window_Driver::resize(int X, int Y, int W, int H) {
     if (scaledH <= 0)
       scaledH = 1;
     SetWindowPos(fl_xid(pWindow), 0, scaledX, scaledY, scaledW, scaledH, flags);
+    if (wait_for_expose_value && Fl_Window::is_a_rescale()) {
+        RedrawWindow(fl_xid(pWindow), 0, 0, RDW_INTERNALPAINT); // send WM_PAINT message to window
+    }
   }
 }
``` 

But not quite sure if that will not affect something else.

**Comment by Albrecht-S** [comment]
Thanks, @lesha-red, for your analysis (debugging) and the patch. This is always appreciated, at least as a start.

I'll try your patch later (not today, please don't hold your breath) to see if it fixes the issue on my system.

@ManoloFLTK can hopefully check and verify this.

**Comment by ManoloFLTK** [comment]
@lesha-red The commit mentionned above should fix the problem. Please, close issue if you confirm.

@Albrecht-S I've tested the fix under Windows 11. Could you, please try with Windows 10?

**Comment by Albrecht-S** [comment]
@ManoloFLTK wrote:
> @Albrecht-S I've tested the fix under Windows 11. Could you, please try with Windows 10?

Yep, tested on Windows 10 (in Virtualbox VM) and it works flawlessly.

1. I checked the commit **before the fix** and I could **reliably** cause the issue by resizing the Virtualbox guest window.
2. I checked current master (dd6b9b90ee57c8020f308435a213a0d6c6c72501) and I could **no longer** cause the issue by resizing the Virtualbox guest window.

Thanks for fixing this.

@cstkingkey I'm glad to read that this fixes your issue as well.
