### ISSUE TITLE
Broken "cube" demo

### ISSUE THREAD

**Issue by SmallJoker** [fltk/fltk#762]
**Describe the bug**

The top `cube` test application originates from FLTK 1.4.0 commit b1ab37e and the bottom one from 1.3.8 (released version). The cubes of the current master branch do not render properly until the window is resized.

https://github.com/fltk/fltk/assets/1497498/23882f77-e09d-45ff-9bfd-85997cfee7e7

However, when forcing software rendering, with `LIBGL_ALWAYS_SOFTWARE=1 ./bin/test/cube` this (viewport?) issue does not occur. Instead, the Z order now seems to be messed up. Again the 1.4.0 test on top and 1.3.8 on the bottom.

![software rendering](https://github.com/fltk/fltk/assets/1497498/8b186678-f592-4ea6-95ce-eeb2d3df2efe)

**To Reproduce**

1. Compile and compare the `cube`
2. See the rendering issue

**FLTK Configure / Build Options**

(used versions noted above)

 * Release build target
 * `OPTION_USE_GL=1` (default)
 * `OPTION_USE_THREADS=1` (default)
 * `OPTION_USE_XFIXES=1` (default)
 * `OPTION_USE_XFT=1` (default)
 * Without Wayland support
 * Without Pango
 * Without Cairo

**Operating System / Platform:**

 * Ubuntu 22.04
 * GCC 11.3.0
 * X11, xfwm
 * AMD GPU

Interestingly, the other OpenGL application (fractal) does produce acceptable results.

EDIT: I tried to bisect this issue but it appears to be introduced with master and is not present on stable-1.3 Furthermore, there are various compiling issues in older versions (Y2011) that make bisecting a lot harder.

**Comment by Albrecht-S** [comment]
@SmallJoker Thank you for your report. I can confirm the issue and I set the label "bug" with low priority.

So far I found out that the failed rendering is caused by the new feature in FLTK 1.4 that you can draw normal FLTK widgets **_over the OpenGL scene_** - which is demonstrated in `test/cube.cxx`.

The code that causes the issue is [in cube.cxx, line 126](https://github.com/fltk/fltk/blob/e12eb99b5dc272f0d11eda4be60e5198430b4c4f/test/cube.cxx#L126):
```

  // if an OpenGL graphics driver is installed, give it a chance
  // to draw additional graphics
#if HAVE_GL
  Fl_Gl_Window::draw();
#endif
```

If this statement is comment out the cubes are rendered correctly, but - as expected - the normal button labeled "FLTK over GL" is not shown. It can be clicked though since it **exists** in the window (if you "know" where to click).

@MatthiasWM Any ideas how to fix this?

**Comment by ManoloFLTK** [comment]
I can add that the same problem occurs with Wayland and with the X11 branch of the Wayland/X11 hybrid library.
However, no problem with macOS, and no problem with X11 under macOS (via XQuartz) which is strange.

**Comment by MatthiasWM** [comment]
Sorry, obviously my thing. I will dig into this. It may simply be that the gl color is still set to transparent from rendering the button.

**Comment by MatthiasWM** [comment]
Thanks for looking at the issue. In general, everything that may be changed in the OpenGL state by FLTK should be queried and later restored. OpenGL `glGetIntegerv(GL_DEPTH_BITS, &bits);` etc. for that. I will try to get that fixed ASAP.

**Comment by ManoloFLTK** [comment]
I believe now the  correct place for the code that disables `GL_DEPTH_TEST` is in class `Fl_OpenGL_Display_Device` rather than class `Fl_OpenGL_Graphics_Driver` as in the patch above. That would give this overridden member function:
```
void Fl_OpenGL_Display_Device::set_current() {
  Fl_Surface_Device::set_current();
  depth_test_ = glIsEnabled(GL_DEPTH_TEST);
  if (depth_test_) glDisable(GL_DEPTH_TEST);
}
```

**Comment by MatthiasWM** [comment]
[79d3b8d](https://github.com/fltk/fltk/commit/79d3b8d69d019ffc19c63eba621dd8d10560e47b) should fix it. I did not put this in the device code because this is a specific function of the GL window, and only used for rendering the FL Widget layer, not for the window in general. But I may be wrong about that.

**Comment by ManoloFLTK** [comment]
The solution involving the device code was born out of my GL ignorance. It makes much more sense to save, change, and restore GL bit states inside the GL window code.

**Comment by SmallJoker** [comment]
Thank you for the fix. With software rendering, the Z-order is now correct (image in first post). However, the problem shown in the video is yet not solved on the following hardware:

```
OpenGL renderer string: AMD Radeon RX 560 Series (polaris10, LLVM 16.0.6, DRM 3.42, 5.15.0-78-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.2.0-rc1
OpenGL core profile shading language version string: 4.60
```

.. but does work correctly with software rendering and an Intel graphics card (different PC):

```
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL core profile version string: 4.2 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 4.20
```

Also overwriting the reported OpenGL version ( `MESA_GL_VERSION_OVERRIDE=2.0 ./bin/test/cube`) did not change anything. Might this be a driver issue or is the Fl_OpenGL* relying on special OpenGL features?

**Comment by MatthiasWM** [comment]
Does commenting out the lines 
```
  // if an OpenGL graphics driver is installed, give it a chance
  // to draw additional graphics
#if HAVE_GL
  Fl_Gl_Window::draw();
#endif
```
in cube.cxx fix the issue?

**Comment by SmallJoker** [comment]
@MatthiasWM No. Unfortunately the issue persists after commenting `Fl_Gl_Window::draw();`. I also double-checked the 1.3.8 demo again which does indeed work correctly.

Here is the output of `valgrind --log-file="valgrind.txt" --leak-check=full ./cube` (patched file) if it helps in any way: [valgrind.txt](https://github.com/fltk/fltk/files/12263799/valgrind.txt)

**Comment by ManoloFLTK** [comment]
@SmallJoker This observation
>  I also double-checked the 1.3.8 demo again which does indeed work correctly.

tells us the problem comes from another of the changes introduced in FLTK 1.4.
A possibility is text drawing which changed. Could you, therefore, comment out the text drawing code in `cube.cxx` and report here whether the cube draws correctly? These lines inside function `cube_box::draw()` need being commented out :
```
  /*gl_font(FL_HELVETICA_BOLD, 16 );
  gl_draw(wire ? "Cube: wire" : "Cube: flat", -4.5f, -4.5f );*/
```
That change is to be done, please, with and without the previous change to comment out `Fl_Gl_Window::draw();`.

**Comment by SmallJoker** [comment]
@ManoloFLTK 

 * With `Fl_Gl_Window::draw`, `gl_font` and `gl_draw` commented
     * Works correctly: 
       ![demo working all uncommented](https://github.com/fltk/fltk/assets/1497498/cfa5ca9d-46ab-4324-a7f9-ce247b523874)
 * With only `gl_font` and `gl_draw` commented
     * Works correctly:
        ![demo working gl_font gl_draw](https://github.com/fltk/fltk/assets/1497498/508e0636-72a0-4f61-b4cb-f9ce7202802e)
 * With only `Fl_Gl_Window::draw` commented
     * Same as shown in the video in the first post
 * Vanilla
     * Same as shown in the video in the first post
 
`gl_draw` (for text) breaks the rendering. `GL_DEPTH_TEST` does not seem to make any difference.

**Comment by ManoloFLTK** [comment]
@MatthiasWM May be you'll be able to find what's wrong in the new text drawing code which is texture based?

**Comment by MatthiasWM** [comment]
@ManoloFLTK Sure, I'll take a look at it. It's probably similar to the Z-buffer fix earlier that changed some parameters without pushing them first.

**Comment by MatthiasWM** [comment]
Ok, so I can't replicate this on my virtual machine, and I only see two functions that manipulate the GL state. The first one, `int gl_texture_fifo::compute_texture(const char* str, int n)`, is probably not it because it is only called three times and the texture is buffered.

The second function, `void gl_texture_fifo::display_texture(int rank)`, is the likely culprit, but after reading through it over and over again, I can't find the issue. The state stack seems to be treated correctly, and the most important settings are saved. I would now go and reduce the function by commenting out calls until the rendering is no longer distorted, but since the bug is not showing on my setup, I have to hand that work back to Manolo, SmallJoker, or Albrecht. Sorry.

`src/gl_draw.cxx:337`, https://github.com/fltk/fltk/blob/5bcd6ca8f2578b959f64d12334cb5454d840ae7d/src/gl_draw.cxx#L337

**Comment by Albrecht-S** [comment]
> I have to hand that work back to Manolo, SmallJoker, or Albrecht

Sorry, I can't help either. The cube demo works now well on my Linux (Debian 12 / Bookworm) system with Intel graphics, using either X11 or Wayland.

FTR: Git current master, commit 5bcd6ca8f2578b959f64d12334cb5454d840ae7d.

**Comment by ManoloFLTK** [comment]
I can't replicate the problem either, so can't try modified code.

One last remark, if I may. Functions `gl_texture_fifo::compute_texture()` and `gl_texture_fifo::display_texture()` are used when function`cube_box::draw()`calls `gl_draw()` and also by the widget drawing procedure via Fl_Gl_Window::draw() which also calls `gl_draw()`. Thus, I see `gl_draw()` work if bracketted by `Fl_Gl_Window::draw_begin()/draw_end()`and fail if called directly. What `draw_begin()` does in addition is `glDisable(GL_TEXTURE_2D)`  and `glEnable(GL_POINT_SMOOTH)`. Matthias: does that make some sense to you ?

**Comment by erco77** [comment]
Just to chime in I couldn't replicate either, even with the original code as it was when the issue is open, so I'd be of no help.. but I have an older ubuntu 20.04 LTS with X.

If need be I might be able to throw together an AMD system with 22.x if it's important to have a dev system to test with, and perhaps give one of the devs access.

**Comment by ManoloFLTK** [comment]
@SmallJoker Could you, please, try this small source code change?
In file `src/gl_draw.cxx`, function `gl_texture_fifo::display_texture(int)` add 2 statements
```
glDisable(GL_TEXTURE_2D);
glEnable(GL_POINT_SMOOTH);
```
after line # 351
```
  glPushAttrib(GL_ENABLE_BIT | GL_TEXTURE_BIT | GL_COLOR_BUFFER_BIT);
```

and report here whether that solves the issue with the AMD driver.

**Comment by SmallJoker** [comment]
@ManoloFLTK Unfortunately that did not change anything. The minimal working code that I could find is the following:

```diff
diff --git a/src/gl_draw.cxx b/src/gl_draw.cxx
index e6adaa1..663702a 100644
--- a/src/gl_draw.cxx
+++ b/src/gl_draw.cxx
@@ -339,9 +339,9 @@ void gl_texture_fifo::display_texture(int rank)
   //setup matrices
   GLint matrixMode;
   glGetIntegerv (GL_MATRIX_MODE, &matrixMode);
-  glMatrixMode (GL_PROJECTION);
+  /*glMatrixMode (GL_PROJECTION);
   glPushMatrix();
-  glLoadIdentity ();
+  glLoadIdentity ();*/
   glMatrixMode (GL_MODELVIEW);
   glPushMatrix();
   glLoadIdentity ();
@@ -384,8 +384,8 @@ void gl_texture_fifo::display_texture(int rank)
   glPopAttrib();
 
   // reset original matrices
-  glPopMatrix(); // GL_MODELVIEW
-  glMatrixMode (GL_PROJECTION);
+  /*glPopMatrix(); // GL_MODELVIEW
+  glMatrixMode (GL_PROJECTION);*/
   glPopMatrix();
   glMatrixMode (matrixMode);
 #if HAVE_GL_GLU_H
```

Which produces the following output: (note: no text on the overlay button)

![minimal working example](https://github.com/fltk/fltk/assets/1497498/a9a83625-d9c0-4438-97e6-35dde3b9d785)

There must be something strange going on with the matrix calculations - or its push/pop stack.

**Comment by MatthiasWM** [comment]
No, that seems correct to me. It first saves the current matrix mode, then pushes both relevant matrices, and later pops them in the correct order, then restores the original matrix mode.

@SmallJoker *Test A*: It's a far reach, but could you please restore the last version and add the line
```
  glMatrixMode (GL_MODELVIEW);
```
before this (line 387, I think):
```
glPopMatrix(); // GL_MODELVIEW
```
The original code is correct, but maybe there is some side effect or driver bug?!

If that doesn't do it, I can sent you more lists of lines to comment out until we find the one line that messes everything up. Not sure if you have the patience for that though 😂. Anyway, if you are up for it, here we go:

*Test B*: Restore the original code, comment out lines 352 to 384 (glDisable (GL_DEPTH_TEST); to glPopAttrib();)

If the 3D rendering is good, continue with Test D.

*Test C*: Restore the original code, replace line 351 (`glPushAttrib(GL_ENABLE_BIT | GL_TEXTURE_BIT | GL_COLOR_BUFFER_BIT);`) with `glPushAttrib(GL_ALL_ATTRIB_BITS);`.

If the 3D rendering is good now, stop here and let us know.

*Test D*: Restore the original code and replace line 374 (`float oy = pos[1] + height - Fl_Gl_Window_Driver::gl_scale * fl_descent();`) with `float oy = pos[1] + height;`.

If the 3D rendering is good now, stop here and let us know. Moving that line before the `glBegin()` line may solve the issue, even if I don't know why.

*Test E*: Restore the original code and comment out 368 to 383. No text is rendered, but is the 3D rendering ok?

*Test F*: Comment out line 367 as well.

*Test G*: Comment out line 366 as well.

I wonder if we will be able to find that issue 😁.

**Comment by ManoloFLTK** [comment]
@SmallJoker Could you, please, apply this patch and report what happens? TIA

[issue762.patch](https://github.com/fltk/fltk/files/12270043/issue762.patch)

**Comment by SmallJoker** [comment]
@ManoloFLTK Yes, that fixes the rendering issue. Thank you very much. The application now looks and functions correctly.

---

@MatthiasWM For the sake of completeness, here are the testing results:

A) Applied the change to the current master, no change. 
B) `width` is also used within `#if HAVE_GL_GLU_H` which I now removed as well. The rendering issue persists.
C) No change, still broken.
D) Still broken
E) Same procedure and result as B)
F) Still broken. I commented these lines back and forth to come to my previous findings.
G) Still broken

**Comment by ManoloFLTK** [comment]
@SmallJoker  OK. To conclude, and before I commit a fix to the git repo, can you, please, confirm that applying `issue762.patch` above **and** replacing the first statement of function `gl_texture_fifo::display_texture(int)` by this one:
```
glPushAttrib(GL_TRANSFORM_BIT | GL_ENABLE_BIT | GL_TEXTURE_BIT | 
  GL_COLOR_BUFFER_BIT);
```
works. TIA.

**Comment by MatthiasWM** [comment]
So 'glGetIntegerv (GL_MATRIX_MODE, &matrixMode);' is broken on that driver?

**Comment by ManoloFLTK** [comment]
> So 'glGetIntegerv (GL_MATRIX_MODE, &matrixMode);' is broken on that driver?

Yes, that's what I would understand too, since the patch merely replaces that call by a call to `glPushAttrib(GL_TRANSFORM_BIT)`.

@MatthiasWM Do you agree for me to commit the proposed fix as described above?

**Comment by MatthiasWM** [comment]
> @MatthiasWM Do you agree for me to commit the proposed fix as described above?

Yes. Perfect! Thank you and thanks to @SmallJoker .

**Comment by ManoloFLTK** [comment]
@SmallJoker The commit mentionned above should fix this issue. Please, close issue if you confirm.

**Comment by SmallJoker** [comment]
Thank you @ManoloFLTK and @MatthiasWM. The demo does now work properly on Mesa/radv.
