### ISSUE TITLE
Drawing artifact with round check buttons in menu under Cairo

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#792]
**Describe the bug**
Observing an artefact with round check buttons in menus with Cairo backend.
This is not seen with a pure X11 build, so seems to be related to Cairo drawing.

**To Reproduce**
Run `test/menubar` with basic scheme, gtk+ scheme or oxy scheme.

**Screenshots**
![round_checkbox_artifact_in_menu](https://github.com/fltk/fltk/assets/9895976/807cb8ac-102a-4c83-ba05-9fdd546b95f1)

**FLTK Version**
1.4. git

**FLTK Configure / Build Options**
Linux with Wayland or X11+Cairo.

**Operating System / Platform:**
Ubuntu 20.04

**Linux/Unix Runtime, if applicable:**
 - Wayland
 - X11+Cairo

**Comment by ManoloFLTK** [comment]
I see the same problem with Ubuntu 22.04, but it's absent from Ubuntu 23.04, both with LowDPI and HighDPI. 
With Debian, I see the problem with Debian 12, but it's fixed in Debian testing.

Thus, I'd say, it's a Debian/Cairo bug corrected in recent versions, not an FLTK bug.

**Comment by wcout** [comment]
I cannot confirm this, still see it with an Ubuntu 23.04 VM with all system updates.

**Comment by ManoloFLTK** [comment]
Here is what I get here with Ubuntu 23.04 also in a VM on a Macbook Pro:
![radiomenu](https://github.com/fltk/fltk/assets/41016272/0c391037-0419-408c-aad7-d45a104036ce)

**Comment by wcout** [comment]
No idea, why we have different results under Ubuntu 23.04. Mine is a VirtualBox image under Ubuntu 20.04.

**Comment by ManoloFLTK** [comment]
No clue on my side either. I use UTM and the arm64 architecture in the VMs.

**Comment by MatthiasWM** [comment]
It may have to do with antialiasing setting which in turn may depend on so many things, including the video card driver. Drawing many parallel lines with a distance of 1 pixels is not necessarily the same as filling an area, especially with hires "Retina" type of screens, scaling desktops, and scaling FLTK.

The round down box is drawn using a list of pie, line, and rectf commands in integer space. Seems like the Cairo driver or the final drawing routines are rounding those wrong into screen space. The only solution I see is to make those drawing functions overlap by a pixel or so, so that rounding errors still draw a fully filled shape.

**Comment by Albrecht-S** [comment]
On my Debian 12 (Bookworm) system running Gnome/Wayland using the Wayland backend I can confirm these issues - at different screen scaling values. However, I don't see issues at scaling factors 1.0 and 2.0 which makes me assume that Matthias' info is the cause of the artifacts. As far as I know we're drawing parallel horizontal lines with different line widths to make sure they are adjacent. That, together with maybe Cairo's "pixel rounding" and maybe antialiasing seems to cause the artifacts.

@ManoloFLTK If that's true, do you know if antialiasing is on when parallel horizontal lines or rects are drawn and which line width is used for a one-pixel wide line? Is it 0 (zero) or 1 (one)? We know that line width 0 can cause issues with some graphics drivers, or - maybe - X11 graphics? I'm not sure. We should also verify that we are really filling the box here with horizontal lines.

**Comment by Albrecht-S** [comment]
Further tests with background color `red` and the X11 backend reveal that it's really the background color "shining through" the box:

![radio2](https://github.com/fltk/fltk/assets/26235500/2d6327f3-5095-4671-ac5b-1afa5cf96d59)

As you can see in the highlighted `Pi` box there's no artifact but in the one with the red background `Mu` you can see the light red line. This screenshot has probably been taken at 170% scaling. And again, I can't see artifacts at 200%.

**Comment by ManoloFLTK** [comment]
@wcout Do you have to scale with Ctrl-+ to some value > 100% and < 200% to reveal the issue?

**Comment by wcout** [comment]
> @wcout Do you have to scale with Ctrl-+ to some value > 100% and < 200% to reveal the issue?
No, I get it also with 100%. Not with 200% but again with 300%.

As @MatthiasWM and @Albrecht-S mentioned antialiasing I just tested a change in Fl_Cairo_Graphics_Driver.cxx::pie() to set CAIRO_ANTIALIAS_NONE. And it really made the artifact go away! Of course this was just a proof, that it has to do with antialiasing, and may have other regressions now.

**Comment by MatthiasWM** [comment]
In `src/fl_round_box.xx`, lines 58 and 60, we calculate the center of the round box using a division by two on an integer value, which will set the center 0.5 pixels too high for odd diameters. Adding one more pixel to the height (or width in 60) of fl_rect should fix the background shining through without disturbing the arc drawing if we move the FILL part before the ARC part. We could also add 1 only if the height/width is an odd number.

Sorry, I don't have Cairo installed to test this out.

**Comment by ManoloFLTK** [comment]
@wcout The issue should be fixed with the commit mentionned above. Please, close issue if you confirm.

**Comment by MatthiasWM** [comment]
I am not happy with that solution. You are switching antialiasing off, making the arcs really ugly. Why use Cairo if you don't use antialiasing? Could you please try my suggestion changing the `w<h` test into `w<=h` and moving the FILL code before the outline drawing. Maybe the enlarged rect is not even needed?

**Comment by MatthiasWM** [comment]
Ok, so this draws a skinny horizontal line before drawing arcs and pies. It's not perfect and a tiny overshooting corner can beset in heavily zoomed and antialiased graphics, but I don't see how else to fix this. I can see it on macOS even without Cairo.

@ManoloFLTK What do you think?

```
static void draw(int which, int x,int y,int w,int h, int inset, Fl_Color color)
{
  if (inset*2 >= w) inset = (w-1)/2;
  if (inset*2 >= h) inset = (h-1)/2;
  x += inset;
  y += inset;
  w -= 2*inset;
  h -= 2*inset;
  int d = w <= h ? w : h;
  if (d <= 1) return;
  fl_color(color);
  if (which == FILL) {
    if (w < h)
      fl_rectf(x, y+d/2, w, h-(d&-2)+1);
    else if (w > h)
      fl_rectf(x+d/2, y, w-(d&-2)+1, h);
    else
      fl_xyline(x, y+d/2, x+w);
  } else {
    if (w < h) {
      if (which != UPPER_LEFT) fl_yxline(x+w-1, y+d/2-1, y+h-d/2+1);
      if (which != LOWER_RIGHT) fl_yxline(x, y+d/2-1, y+h-d/2+1);
    } else if (w > h) {
      if (which != UPPER_LEFT) fl_xyline(x+d/2-1, y+h-1, x+w-d/2+1);
      if (which != LOWER_RIGHT) fl_xyline(x+d/2-1, y, x+w-d/2+1);
    } else {
      if (which == UPPER_LEFT) fl_point(x, y+d/2);
      if (which == LOWER_RIGHT) fl_point(x+w-1, y+d/2);
    }
  }
  void (*f)(int,int,int,int,double,double);
  f = (which==FILL) ? fl_pie : fl_arc_i;
  if (which >= CLOSED) {
    f(x+w-d, y, d, d, w<=h ? 0 : -90, w<=h ? 180 : 90);
    f(x, y+h-d, d, d, w<=h ? 180 : 90, w<=h ? 360 : 270);
  } else if (which == UPPER_LEFT) {
    f(x+w-d, y, d, d, 45, w<=h ? 180 : 90);
    f(x, y+h-d, d, d, w<=h ? 180 : 90, 225);
  } else { // LOWER_RIGHT
    f(x, y+h-d, d, d, 225, w<=h ? 360 : 270);
    f(x+w-d, y, d, d, w<=h ? 360 : 270, 360+45);
  }
}
```

**Comment by ManoloFLTK** [comment]
There are still faint lines at 170% and 240%, and it doesn't take care of the oxy and gtk+ schemes.

**Comment by ManoloFLTK** [comment]
This picture shows gtk+ radio menu items scaled to 240% drawn, on the left, with the committed fix (6958e5d) and on the right the same items drawn with the code before this commit, that is, with antialiased graphics. I don't see that the quality of the left side drawing is degraded. The tiny undesired gray lines at right are absent at left.
![fix-no-antialias](https://github.com/fltk/fltk/assets/41016272/2dbb91ee-0c47-4b86-967c-2e17cb518f18)

**Comment by wcout** [comment]
The only scheme that is "degraded" is `oxy`, because it draws a pie with no surrounding arc. But I think this degradation is barley noticeable. Here a comparison at zoom 300% and **additional** 3x magnification:
 
left: new -without  antialiasing / right: old, with antialiasing:
![new_old](https://github.com/fltk/fltk/assets/9895976/01621cb8-322d-4e1d-ba4e-1aeaf66e425e)

**Comment by ManoloFLTK** [comment]
Commit da5331b should fix the issue without fiddling with antialiasing at all.

@MatthiasWM This commit takes your concern into account because all calls to fl_antialias(0) are removed.

@wcout Do you confirm you no longer get drawing artefacts? If so, please close issue.

**Comment by MatthiasWM** [comment]
I still have an ever so faint line in the very outer circle of the radio menu button, but I think that that is perfectly acceptable for an antialiased display at 240% zoom. Thank you! Looks beautiful.
![Screenshot 2023-10-16 at 15 17 41](https://github.com/fltk/fltk/assets/653993/14866c04-9ba2-4856-ab1a-7d2503074a51)

**Comment by ManoloFLTK** [comment]
@MatthiasWM Right, I'd not seen that. I know the recipe now so could correct that too (15fe9d9).

**Comment by wcout** [comment]
These changes have fixed the issue.

But maybe there is some regression here due the change of drawing small circles?:
![unittest_complex_shapes](https://github.com/fltk/fltk/assets/9895976/80f216dd-d7fd-4bd7-8432-e0c6e1ea14ea)

I don't see the small dots here, even in scales > 100%.
